# Sidebar
[[main]]
    name = "À propos"
    pageRef = "/page/about"
    weight = 10
    params.icon = "user"

[[main]]
    name = "Purpleverse"
    pageRef = "/world"
    weight = 20
    params.icon = "infinity"

[[main]]
    name = "Projets"
    pageRef = "/projects"
    weight = 30
    params.icon = "hash"

[[main]]
    name = "Artblog"
    pageRef = "/artblog"
    weight = 35
    params.icon = "tag"

[[main]]
    name = "Blog"
    pageRef = "/blog"
    weight = 40
    params.icon = "archives"

[[main]]
    name = "Search"
    pageRef = "/page/search"
    weight = 50
    params.icon = "search"

# Social links
[[social]]
    identifier = "tumblr"
    name = "Tumblr"
    url = "https://lullinglore.tumblr.com/about"
    params.icon = "social-tumblr"

[[social]]
    identifier = "gamejolt"
    name = "Game Jolt"
    url = "https://gamejolt.com/@lullinglore"
    params.icon = "link"

[[social]]
    identifier = "youtube"
    name = "YouTube"
    url = "https://youtube.com/@lullinglore"
    params.icon = "social-yt"