# STACK PARAMS #
# SETTINGS
mainSections = ["blog", "artblog"]
math = false #Set to true in frontmatter whenever needed

# WIDGETS
[widgets]

  [[widgets.homepage]]
    type = "search"
  [[widgets.homepage]]
    type = "tag-cloud-topics"
  [[widgets.homepage]]
    type = "tag-cloud-categories"
  #[[widgets.homepage]]
  #  type = "newsletter-sidebar"
  [[widgets.homepage]]
    type = "kofi-button"

  [[widgets.page]]
    type = "search"
  [[widgets.page]]
    type = "toc"
  [[widgets.page]]
    type = "newsletter-sidebar"
  [[widgets.page]]
    type = "kofi-button"
